# Generated by Django 6.1 on 2026-09-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arena", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="description",
            field=models.TextField(max_length=9999),
        ),
    ]
